/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs480project;

/**
 *
 * @author Aileen
 */


import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
 
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.sql.*;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class LogSystem extends javax.swing.JFrame {
    private JTable logTable;
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form LogSystem
     */
    /**
     * Creates new form LogSystem
     */
    public LogSystem() {
        super("Log Event Manager");
        conn = LogConnect.ConnectDB();
        readFile();
 
        List<Log> listLogs = createListLogs();
        TableModel tableModel = new LogTableModel(listLogs);
        logTable = new JTable(tableModel);
 
        logTable.setAutoCreateRowSorter(true);
 
        add(new JScrollPane(logTable), BorderLayout.CENTER);
 
        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();
//        conn = LogConnect.ConnectDB();
//        readFile();
    }
    
    private void update_Table(){
        try{
            String sql = "select * from LinuxEventLogs";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            logTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void readFile(){
        StringTokenizer st; 
        String delim = "]:";
        try{
        FileInputStream fstream = new FileInputStream("C:\\Users\\Aileen\\Documents\\NetBeansProjects\\CS480Project\\src\\auth2.log");
        BufferedReader br = new BufferedReader(new InputStreamReader(fstream));
        String strLine;
        /* read log line by line */
       //br.readLine();
       //strLine = null;

        while ((strLine = br.readLine()) != null)   {
            /* parse strLine to obtain what you want */

//            st = new StringTokenizer( strLine, delim );
            String[] tokens = strLine.split( delim );
            String[] firstHalfToken = tokens[0].split(" ");
            sendToDatabase( firstHalfToken, tokens[1] );

            
        }
        System.out.println("done!");
        fstream.close();
        br.close();
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }
    
    public void sendToDatabase( String[] array, String secondHalf ){
        try{
            String sql = "INSERT INTO LinuxEventLogs (Month,Date,Time,User,Drive,Event) VALUES(?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
                pst.setString( 1, array[0]);
                pst.setInt( 2, Integer.parseInt(array[1]));
                pst.setString( 3, array[2]);
                pst.setString( 4, array[3]);
                pst.setString( 5, array[4] + "]");
                pst.setString( 6, secondHalf);
                pst.executeUpdate();
                //update_Table();
               // System.out.println("added" + array[4]);
        } catch ( Exception e ){
            System.out.println("im the problem y'all" + e.toString());
        }
    }
    
    public List<Log> createListLogs() {
        List<Log> listLogs = new ArrayList<>();
        String query = "SELECT * FROM `LinuxEventLogs`";
        Statement st;
        try{
            st = conn.createStatement();
            rs = st.executeQuery(query);
            Log log;
            while(rs.next()){
                log = new Log(rs.getString("Month"),rs.getInt("Date"),rs.getString("Time"),rs.getString("User"),rs.getString("Drive"),rs.getString("Event"));
                listLogs.add(log);
            }
        }catch(Exception e){
        }
        return listLogs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
